### ISSUE TITLE
Make runsOn required when validating

### ISSUE THREAD

**Issue by gastaldi** [fabric8-launcher/launcher-booster-catalog#210]
This ensures that a booster won't show up in an environment it wasn't meant to run

**Comment by quintesse** [comment]
Wdym by this? I'm not sure I understand the purpose of this issue.

**Comment by gastaldi** [comment]
I opened this issue after seeing that some boosters (specifically the ones that should appear on OSIO only) didn't specify the `runsOn` attribute correctly, making a booster disappear from the environment that was meant to run. 

I believe that by requiring the `runsOn` would make the PR submitter think first on what environments their boosters would run on. 

Feel free to close if that doesn't make sense.

**Comment by quintesse** [comment]
I just don't see how you would make that work. I mean it's perfectly valid for a booster to _not_ have any `runsOn` attribute, right? And on top of that the runtime teams often don't know. They don't care about the `osio` flag for example.

**Comment by quintesse** [comment]
Btw, it does make me think that my suggestion a couple of weeks ago to somehow uncouple the booster definitions from the "list" of available boosters could be useful. Because it's obvious to me that the people who care about the boosters themselves (the runtime teams) and the people who care about _which_ boosters appear in their app (osio, the launcher) are not always the same.

**Comment by kenfinnigan** [comment]
+1 to that

I am completely ignorant as to all the different environments that are possible for `runsOn`

**Comment by gastaldi** [comment]
I am a bit unsure if having two different `lrunsOn` tags makes sense in this context. since OSIO is considered a possible `runsOn` value.

**Comment by quintesse** [comment]
Sure, that's why I said the two got conflated. I don't think OSIO should be a possible `runsOn` value, it just doesn't make sense. They are two different environments with two different objectives, so to speak. You can see it because for OSIO we have to work in the negative: instead of stating which boosters work in OSIO we have to state where the do _not_ work. Because if someone writes `osio` (which guess is what happened?) then that affect our launcher.

Well unless you make the `runsOn` flag required and make everybody write: `starter, pro, local` everywhere. (And if we ever add another value we'll have to add that to all of them too)

So although my suggestion won't win any beauty contests it does separate the concerns: we manage the `launcherRunsOn` tags and they manage their `osioRunsOn` tags and changes to one won't affect the other. (Btw, perhaps `osioRunsOn` doesn't make sense because they don't use different clusters, perhaps a simple `osio: true` tag would do in their case)

(I'd actually prefer having completely separate lists instead of using these tags, but I can't for now see a way of doing that while keeping things simple)

**Comment by gastaldi** [comment]
Superseded by https://github.com/fabric8-launcher/launcher-booster-catalog/issues/242
