### ISSUE TITLE
Build the boosters when validating a PR

### ISSUE THREAD

**Issue by gastaldi** [fabric8-launcher/launcher-booster-catalog#211]
It would be nice if the PR validation could build the boosters (mvn clean install skipping tests or not) to detect at the very least if the artifacts are present in the public repositories.

**Comment by Ladicek** [comment]
Not sure if you started working on this, but I quickly threw this together: https://github.com/rhoar-ci/booster-catalog-verifier

**Comment by Ladicek** [comment]
I mean, I'm not running it anywhere (yet :-) ), we can discuss that.

**Comment by gastaldi** [comment]
@Ladicek I haven't started working on this yet.
Suggestion: Right now we call https://github.com/fabric8-launcher/launcher-booster-catalog/blob/master/validate.sh to validate the PR, maybe you may want to put your code here: https://github.com/fabric8-launcher/launcher-booster-catalog-service

**Comment by Ladicek** [comment]
The code I have has a couple of dependencies that probably wouldn't be a good fit for the booster catalog service (Maven Invoker, JGit). I know the catalog service is able to clone Git repositories itself, and I could replace Maven Invoker by using `ProcessBuilder`; I didn't do that, because we already have a piece of code using Maven Invoker and JGit that I was able to just copy :-) And I'd also have to rewrite it from JUnit to a good old Java method. Nothing insurmountable, but I don't quite have the time now. Feel free to steal from me :-)

**Comment by maxandersen** [comment]
you might also want to ensure you use your custom settings.xml and ensure it will override any default setup.

**Comment by Ladicek** [comment]
Submitted https://github.com/fabric8-launcher/launcher-booster-catalog/pull/225

**Comment by gastaldi** [comment]
Fixed in https://github.com/fabric8-launcher/launcher-booster-catalog/pull/225
