### ISSUE TITLE
[.NET Core 2.0] Add boosters for .NET Core 2.0

### ISSUE THREAD

**Issue by omajid** [fabric8-launcher/launcher-booster-catalog#78]
This is just a tracker for adding boosters for .NET Core 2.0 to the catalog so .NET Core appears on the new project wizard on openshif.io

Some questions:
- Which boosters are simplest/easiest for getting something small up and running?
- What boosters are users likely to find the most useful?
- What does an optimized (for developer productivity *and* low resource usage) implementation of something like the [http-rest booster](https://github.com/openshiftio/booster-catalog/tree/master/rest-http) look like? Does it involve ASP.NET Core MVC or something less complicated?
- In terms of language, do we need anything other than C#? Are either VB or F# worth looking into?

See also https://github.com/fabric8-quickstarts/dotnet-example/pull/1 for a something similar but for the older quickstart approach.

cc @aslicerh @DonSchenck

**Comment by jstrachan** [comment]
I'm not sure what the policy is for adding new Missions so that we can add new boosters that don't fit the current list of missions.

@omajid I wonder if the http-rest is the best place to start; just a little quickstart doing some simple REST API? You could do one super simple and another using the more complicated ASP.NET Core MVC? Though TBH I'd be pretty happy with just 1 booster in the catalog that worked in fabric8/OSIO ;)

I guess C# is the most important; but having a booster for VB & F# would be handy eventually.

**Comment by gastaldi** [comment]
@omajid You can find instructions on how to create a new Booster here: https://github.com/openshiftio/appdev-documentation/wiki/Creating-a-new-Booster

**Comment by omajid** [comment]
> I wonder if the http-rest is the best place to start; just a little quickstart doing some simple REST API? 

In that case: https://github.com/fabric8-quickstarts/dotnet-example is probably already good enough.

**Comment by gastaldi** [comment]
Closing this issue, as I believe it's in the wrong repository. Let's discuss about this in the [fabric8-launcher forum](https://groups.google.com/forum/#!forum/fabric8-launcher)
